gem 'hpricot', '>= 0.8.1'
require 'hpricot'
require 'rubypoint/presentation'
require 'rubypoint/element'
require 'rubypoint/file'
require 'rubypoint/relationship'
require 'rubypoint/textfield'
require 'rubypoint/slide/slide'
require 'rubypoint/slide/rel'
require 'rubypoint/docProps/app'
require 'rubypoint/content_types_xml'
require 'rubypoint/ppt/presentation'
require 'rubypoint/ppt/rels/presentation_rel'